apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
      - name: student-management-container
        image: achraf31/student-management:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: student-management-service
spec:
  type: NodePort
  selector:
    app: student-management
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30082
